apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-dp
    labels:
        app: devsecops
spec:
    replicas: 2
    selector:
        matchLabels:
            app: devsecops
    template:
        metadata:
            labels:
                app: devsecops
        spec:
            imagePullSecrets:
               - name: ecr-secret
            containers:
                - name: devsecops-container
                  image: 187868012081.dkr.ecr.ap-south-1.amazonaws.com/devsecops:27c7fecae6204187fe7759af8868645c19a85b80
---
apiVersion: v1
kind: Service
metadata:
    name: my-svc
    labels:
        app: devsecops
spec:
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: devsecops
    type: NodePort
